### ISSUE TITLE
Feature - Logotype page redesign

### ISSUE THREAD

**Issue by mxuwku** [scania/corporate-ui-site#100]
**What is your feature request?**  
A new page to view logotype guidelines

Main branch `Improvement/logotype_page`

1.  `Improvement\logotype_page_two_columns`
- [x] Image right content type
- [x] Multi image columns(Two images+ text left)
- [x] Label above image
- [x] Caption under image
- [x] background color on negative image
- [x] Two column setup
- [x] List with two columns inside the text
- [x] Download links
- [x] Description on top
#106 
scania/corporate-ui-cms#19

2.
- [ ] Black background on negative images part
- [ ] Header with border red left

Possible options:
- Headline options (h1-h6 and strong)
- Image sizing option
- Image size should always be set by the image it self
- Set Background in cms
- Possible to set alt text in cms

**Describe the solution you'd like**  
_![Logotype page](https://user-images.githubusercontent.com/39794299/94239627-62c82700-ff12-11ea-8ca0-41c09be22b90.png)_

**Comment by mmexvr** [comment]
This issue is closed because of the new design of sdds
