### ISSUE TITLE
Feature - What's New

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui-site#105]
**What is your feature request?**  
A layout needed for "What's new" page

**Describe the solution you'd like**  
Wireframe layout
![Whats new wireframe](https://user-images.githubusercontent.com/1199101/95195555-0351fd00-07d7-11eb-85ec-6444bff2d2f6.png)

**Additional context**  
_Add any other context or screenshots about the feature request here._

**Comment by mmexvr** [comment]
Closing this, old design
