### ISSUE TITLE
Improvement - page should always open at top, not scrolling

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui-site#128]
Scenario:

User scrolls on a detail page; Foundation Spacing.
User then navigates to another detail page, Foundation Typography, via the left navigation.
User then navigates back to the Foundation Spacing via the left navigation and then ends up where it was when the user first left that specific page.
It feels more natural if the detail page always start at the top.

**Comment by masceh** [comment]
This includes the page the user is scrolling to also.
