### ISSUE TITLE
Improvement - SDDS title

### ISSUE THREAD

**Issue by alexlioliopoulos** [scania/corporate-ui-site#146]
In some resolutions, the title Scania Digital Design System is pushed to 2 lines

![sdadas](https://user-images.githubusercontent.com/76053160/102224614-79b16080-3ee6-11eb-8429-f02431621533.PNG)

**Comment by mmexvr** [comment]
I would guess this issue is related with the default scrollbar in windows

**Comment by alexlioliopoulos** [comment]
Yes exactly, but how are we fixing it?

**Comment by helloimela** [comment]
Fixed in #173
