### ISSUE TITLE
Improvement -<br/> is not working

### ISSUE THREAD

**Issue by alexlioliopoulos** [scania/corporate-ui-site#153]
<br/> is not working anymore!

**Comment by helloimela** [comment]
> is not working anymore!

@alexlioliopoulos  can you show in what page is that, and which part of the page

**Comment by alexlioliopoulos** [comment]
In multiple pages.

For example in Getting Started > Design. I am attaching the "code" and the output.

![ela1](https://user-images.githubusercontent.com/76053160/102232790-d6654900-3eef-11eb-84fc-9d33033d6003.PNG)
![ela2](https://user-images.githubusercontent.com/76053160/102232793-d6fddf80-3eef-11eb-99c5-e25b63c97741.PNG)

**Comment by helloimela** [comment]
Okay @alexlioliopoulos It will be fixed soon
Fix in #141

**Comment by alexlioliopoulos** [comment]
Works!
