### ISSUE TITLE
Bug - Tab bar on Foundation › Typography

### ISSUE THREAD

**Issue by niklasros** [scania/corporate-ui-site#154]
**Describe the bug**  
_The tab bar is placed on two rows, making the entire page broken._

**To Reproduce**   
_Steps to reproduce the behavior:_  
1. Go to 'https://digitaldesign.netlify.app/foundation/foundation-typography' on a mobile device
2. See error

**Expected behavior**  
_Tab bar should only be one one row_

**Screenshots**  
![tab-bar-typography](https://user-images.githubusercontent.com/59045455/102230615-66ee5a00-3eed-11eb-9b95-16eba5380a0f.jpeg)

**Smartphone information**  
 - Device: [iPhone 8]
 - OS: [e.g. iOS 14.1]
 - Browser [Safari / Chrome]

**Comment by helloimela** [comment]
@niklasros If it doesn't fit because of long text, how it should behave? Horisontal scrolling? I think there is not enough space for the 2 last links, that's why it goes down

**Comment by niklasros** [comment]
> @niklasros If it doesn't fit because of long text, how it should behave? Horisontal scrolling? I think there is not enough space for the 2 last links, that's why it goes down

I understand. Horizontal scrolling should be applied to the tab bar.
