### ISSUE TITLE
Improvement - Type scale text width

### ISSUE THREAD

**Issue by niklasros** [scania/corporate-ui-site#163]
**Describe current situation**  
_The Type scales text width on Foundation Typography is too big._

**Describe the improvement**  
_Align the width with all other body text fields on the page._

**If applicable, please provide steps to reproduce**
_Steps to reproduce the behavior:_  
1. Go to 'Foundation Typography'
3. Scroll down to 'Type scale'

**Screenshot**  
<img width="1183" alt="type-scale-text" src="https://user-images.githubusercontent.com/59045455/102317882-a746ea00-3f78-11eb-8b85-6d840030520c.png">

**Additional context**  
_https://digitaldesign.netlify.app/foundation/foundation-typography_

**Comment by helloimela** [comment]
Solved from the CMS
