### ISSUE TITLE
Foundation-pictogram-contribute-construct a pictogram-step1 caption continues in a line and overlaps step 2 caption

### ISSUE THREAD

**Issue by pd2001** [scania/corporate-ui-site#167]
**Describe current situation**  
_Describe what the current situation and what problem it is causing for this improvement_

**Describe the improvement**  
_A clear and concise description of what kind of improvement you have in mind._

**If applicable, please provide steps to reproduce**
_Steps to reproduce the behavior:_  

**Screenshots**  
_If applicable, add screenshots to help explain your ideas._

**Additional context**  
_Add any other context about the suggestion here._

**Comment by helloimela** [comment]
Caption overlap has been solved in #141
