### ISSUE TITLE
Bug - Overview Page in Corporate-Ui-Site

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui-site#22]
Right now overview page for the bootstrap components is showing incorrectly.

Overview is using Zoom that works good in Custom-elements but not for Bootstrap components

![image](https://user-images.githubusercontent.com/35451568/70896241-aa6b6b00-1ff0-11ea-9b82-295ab1cccb78.png)

**Comment by awinny** [comment]
Already solved
