### ISSUE TITLE
Feature - c-modal and c-dropdown documentation

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui-site#86]
**What is your feature request?**  
c-modal and c-dropdown component is not in the documentation

**Describe the solution you'd like**  
Since they are available component to use, might be good to have it in the docs.

**Additional context**  
Need to test again before add it to the docs. Or we can just add it and let people try use it.

**Comment by mmexvr** [comment]
Will close this until further design for components and patterns has been added
