### ISSUE TITLE
Feature - New page design ICONS

### ISSUE THREAD

**Issue by mxuwku** [scania/corporate-ui-site#92]
**What is your feature request?**  
A updated design for icons page on SDDS

**Describe the solution you'd like**  
_https://xd.adobe.com/view/c2d08a16-5ea2-4fc2-8b95-b10c58f0c072-9783/_

Tasks:
- [x] Update layout and strapi template
   Should have possibility to add icon as a content in Strapi
   Should accommodate the needs to separate icons in categories
   Should be able to display text and preview icon on each tab
   PR: #97  

- [x] Display detail icon in modal
   Should show modal when click on one icon
   Should show texts and donwload buttons , follow design in XD
   PR: #99 

- [x] Select and download function 
  Should show background color and checkbox on hover
  Should be able to select all and select few icons
  Should be able to download selected icons
  PR: #102 

- [x] Search function
   Should display search input field in the page
   Should filter icons based on search
  PR: #103 

**Additional context**  
Example code can be found within the interactive prototype

**Comment by helloimela** [comment]
Tasks:
- [ ] Update layout and strapi template
   Should have possibility to add icon as a content in Strapi
   Should accommodate the needs to separate icons in categories
   Should be able to display text and preview icon on each tab
- [ ] Select and download function 
  Should show background color and checkbox on hover
  Should be able to select all and select few icons
  Should be able to download selected icons
- [ ] Search function
   Should display search input field in the page
   Should filter icons based on search
- [ ] Display detail icon in modal
   Should show modal when click on one icon
   Should show texts and donwload buttons , follow design in XD
