### ISSUE TITLE
Bug - C-cookies translation not working in Incognito

### ISSUE THREAD

**Issue by helloimela** [scania/corporate-ui-site#93]
**Describe the bug**  
When we access the site in incognito mode, the text in c-cookie is not appearing. Maybe caused by the translation used.

**To Reproduce**   
_Steps to reproduce the behavior:_  
1. Go to digitaldesign.scania.com in incognito mode
2. See error in cookie message

**Expected behavior**  
Should have a default value for text translation. If "lang" is not defined, then use en.json

**Screenshots**  
![image](https://user-images.githubusercontent.com/1199101/93209748-d4f47b00-f75e-11ea-8efd-086a75f687f0.png)

**Desktop information:**  
_Please complete the following information_
 - Browser Chrome
 - Version 85
 - OS: Windows 10

**Additional context**   
Only happens in Incognito mode

**Comment by helloimela** [comment]
This problem is caused by AWS path behavior. Nothing to change in the code.

Please check some requirements below to close this issue:
1. Open https://digitaldesign.scania.com/ in normal and incognito browser.
2. Check if c-cookies banner display correct text
3. Please check if you can download assets from these pages:
   - https://digitaldesign.scania.com/home (download Adobe UI Kit)
   - https://digitaldesign.scania.com/foundation/logotype (all logotype are displayed properly and you can download)
   - https://digitaldesign.scania.com/resources/identity-manual (make sure you can open pdf files)
   - https://digitaldesign.scania.com/resources/ui-kits (download Adobe UI Kit)
4. Please check if these links work to make sure path behavior is working for all folders and subfolders:
https://digitaldesign.scania.com/builds/themes/scania/1.1.3-2/scania-theme.js
https://digitaldesign.scania.com/builds/components/4.1.2-1/corporate-ui.js
https://digitaldesign.scania.com/fonts/scania-sans/ScaniaSans-Regular.ttf
https://digitaldesign.scania.com/icons/0.0.3/ICON_24h_service/06_SIS_24h-emergency-breakdown-service_RGB_54-72px.svg
https://digitaldesign.scania.com/logotype/favicon/apple-icon.png
https://digitaldesign.scania.com/logotype/scania-symbol.png

**Comment by mmexvr** [comment]
Tested every link mention and it works, both in FF and chrome and in incognito
